annotations:
  category: ApplicationServer
apiVersion: v2
appVersion: alpha
dependencies:
  - name: common
    repository: file://../common
    tags:
      - bitnami-common
    version: 1.13.0.1
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami/
    version: 12.1.6
    condition: postgresql.enabled
description: Strapi demo starter
home: https://github.com/luafanti/strapi-demo
maintainers:
  - email: luafanti@gmail.com
    name: Artur Bartosik
name: strapi-demo
sources:
  - https://github.com/luafanti/strapi-demo
version: 0.0.1
